### ISSUE TITLE
What exactly means a `Matrix` as input

### ISSUE THREAD

**Issue by tafia** [AtheMathmo/rusty-machine#108]
Sorry for the very naive question.

I don't understand a `Matrix` as an input like [here](https://github.com/AtheMathmo/rusty-machine/blob/master/src/learning/glm.rs#L92), I was rather expecting a vector.
Could you give some information of what it could mean?

It may be very stupid but looking at [`GenLinearModel::train`](https://github.com/AtheMathmo/rusty-machine/blob/master/src/learning/glm.rs#L117-L120), it looks like for the scenarii where the `full_input` is a square matrix, then the algorithm is much simpler (as `new_beta = full_input.inverse() * z`). I suspect this doesn't really happen as `input` is mostly a vector, else if I'm not wrong we should probably have a check and use the simplified approach.

**Comment by tafia** [comment]
ok, I suppose I got it ...
Just to be sure input is probably a Matrix nxm, with m << n. So it is very unlikely that `full_input` is a square matrix.

**Comment by AtheMathmo** [comment]
Not such a naive question, don't worry!

Yes as you say typically this would be an nxm matrix with m << n. However we don't need the m << n restriction (though the model would likely not work well without special treatment). In general, the `inputs` matrix has each data point in a row - where the columns are often referred to as `features`.

Currently there isn't enough consistency in the library between different model's `inputs` and `outputs`. I'll be trying to address this a little after the error handling is beefed out.

**Comment by tafia** [comment]
Thanks for the answer
