### ISSUE TITLE
Use more `Borrow`s

### ISSUE THREAD

**Issue by tafia** [AtheMathmo/rusty-machine#109]
There are many places where copies are done (via `select_rows` for instance) when a simple borrow would have been enough.

We could probably save some memory by:
- implementing `Borrow` and `AsRef` between `Matrix` and `MatrixSlice(Mut)` (they make sense I think)
- having more generic traits that require `Borrow<T>` or `AsRef<T>` instead of `&T`

Example with `Optimizable`:
```rust
        /// Trait for models which can be gradient-optimized.
        pub trait Optimizable {
            /// The input data type to the model.
            type Inputs;
            /// The target data type to the model.
            type Targets;
            /// Compute the gradient for the model.
            fn compute_grad(&self,
                            params: &[f64],
                            inputs: Borrow<Self::Inputs>,
                            targets: Borrow<Self::Targets>)
                            -> (f64, Vec<f64>);
        }
```

Then we could use `MatrixSlice` instead of `select_rows` [here](https://github.com/AtheMathmo/rusty-machine/blob/master/src/learning/optim/grad_desc.rs#L181-L183).

There are probably many examples.

**Comment by AtheMathmo** [comment]
This is a really, really good suggestion. It will remove a lot of unneeded copying - especially in conjunction with your `get_row` PR that will be merged soon.

I have yet to use `Borrow` and `AsRef` so the differences are lost on me right now. I'll have to do some reading.

I'm happy to work on this issue if you didn't want to.

**Comment by tafia** [comment]
Please do it! You may come up with new suggestions

**Comment by AtheMathmo** [comment]
Ok I'll tackle this one :). I won't be able to tackle it until the weekend (focusing on a presentation for a meetup).

**Comment by AtheMathmo** [comment]
Added a [mirror issue on rulinalg](https://github.com/AtheMathmo/rulinalg/issues/14) to track the implementation there.

**Comment by AtheMathmo** [comment]
Closing this out. We've gone with an alternate approach and wont be able to do something like this until custom DSTs land.
