### ISSUE TITLE
Add confusion matrix to analysis module

### ISSUE THREAD

**Issue by theotherphil** [AtheMathmo/rusty-machine#132]
Not terribly exciting, but it'll be nice to start to fill out the set of standard helper functions.

I plan on adding this.

**Comment by AtheMathmo** [comment]
It's great to see this stuff growing. Thanks for your work on it!

**Comment by AtheMathmo** [comment]
Just wanted to check whether you're still planning on implementing this yourself. I'll keep the issue open even if not so that someone else can grab it. But will add some labels and perhaps edit the body to make clear that someone else can pick it up.

**Comment by theotherphil** [comment]
After a burst of holiday coding I've been busy with real life again for the last few months. I plan on doing some more over Christmas though so I'll get this done then.
