### ISSUE TITLE
Add benchmarks for cross validation

### ISSUE THREAD

**Issue by theotherphil** [AtheMathmo/rusty-machine#137]
I'll do this.

Do you have a policy on the scope of raised issues? The last two I've raised are just small bits of work I intend to do anyway. This could get a bit spammy, but does mean that all planned work is visible as an issue.

**Comment by AtheMathmo** [comment]
Awesome!

> Do you have a policy on the scope of raised issues?

Your approach is really ideal. I like having things broken down so they can be merged and closed quickly. This approach is only an issue if the tasks go stale when you can't finish them. I'm happy to keep track of those issues if it ever arises though.

**Comment by theotherphil** [comment]
Ok, thanks

**Comment by AtheMathmo** [comment]
@theotherphil would you like me to close this issue now?

We have a benchmark to track the cross validation performance. We _could_ add more fine-grained per-function benchmarks but I think that right now these are a little unnecessary?

**Comment by theotherphil** [comment]
I agree, I think what we've got is fine for now.
