### ISSUE TITLE
Improving error handling for decomposition

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#16]
The current decomposition techniques panic when decomposition can not be computed.

Instead, we should return Results. This will allow the code to handle decomposition errors specially - making it much easier to debug algorithms where numerical instability occurs.

For example with the upcoming implementation of GMMs the covariance may be ill-conditioned and so we cannot decompose it to get the inverse. If we had a Result we can provide more accurate error messages.

**Comment by AtheMathmo** [comment]
Have opened a branch for this: `decomp-errors`. Have cleaned up the errors for most of the decomposition, but have not for LUP decomposition or inverses.

I plan to implement a `Result` for the LUP decomposition. But I'm unsure about inverses. It will affect a lot of other code - I'd appreciate some outside input on this issue!

**Comment by qinwf** [comment]
Read some docs and codes, and find that many matrix function may panic. It will be hard to use when we are going to cross FFI boundary.

**Comment by AtheMathmo** [comment]
Thanks for commenting!

Indeed a lot (too many) of the current methods panic. However I am not sure that we should be replacing all of these with `Result`s. In my head I wanted to make a lot of the current `assert` calls `debug_assert` - mostly for release performance.

Could you explain a little more about how panics interact with the FFI boundary? I definitely want to explore this in the future but have done little research thus far. What would be your suggested solution?

**Comment by qinwf** [comment]
What about providing two function, one for panic and one for Result. But this may duplicate some code. 

I use rusty-machine to work with R, but if Rust panic, it will be undefined behavior. 

we can `catch_panic` on every call to Rust.

Or check input before passing a matrix to Rust. If every input needs to be checked, it just feel like that all these functions are `unsafe` to used for FFI cases.

**Comment by AtheMathmo** [comment]
First of all it's awesome that you're looking to use rusty-machine! I'm more than happy to try and help that happen - though it may be worth opening up a separate ticket for this. And an FFI is a little off my radar right now.

As for your comment: it looks like for now that the easiest way to handle this is [described here](https://doc.rust-lang.org/book/ffi.html#ffi-and-panics). We essentially spawn a new thread to run the code and can check if it panics this way. There is also [this method](https://doc.rust-lang.org/beta/std/panic/fn.recover.html) in the works. I don't want to duplicate the methods as this will blow the code up dramatically and make it difficult to maintain.

If you want to work on an FFI I'll do my best to provide support. I should add though that it may be easier to use an FFI to a more mature library!
