### ISSUE TITLE
Add Basic Transformers

### ISSUE THREAD

**Issue by sinhrks** [AtheMathmo/rusty-machine#163]
Related to #158. I think below transformers are useful.

- min / max scaling (scaling inputs to [0, 1] using min/max)
- normalize (each rows are rescaled to have the same norm)
- standardize (transform to zero-mean and unit-variance)

**Comment by AtheMathmo** [comment]
Quite a few of these [already exist](https://athemathmo.github.io/rusty-machine/doc/rusty_machine/data/transforms/index.html).

I'd welcome a PR to add a normalized transform :)

**Comment by sinhrks** [comment]
ah, haven't noticed. gr8:)

**Comment by AtheMathmo** [comment]
I am going to close this @sinhrks . Feel free to reopen an issue for the `normalize` transformer.
