### ISSUE TITLE
Linear regression using gradient descent

### ISSUE THREAD

**Issue by nikhilmitrax** [AtheMathmo/rusty-machine#197]
I was wondering why Linear Regression was implemented using gradient descent instead of using OLS. Is there a specific reason for that?

I'd be inclined to think that the closed form solution might be faster than iteratively optimizing.

**Comment by AtheMathmo** [comment]
The default implementation uses OLS: https://github.com/AtheMathmo/rusty-machine/blob/d049f60a3b55184e4d15098c7aa8db04afa76c06/src/learning/lin_reg.rs#L85-L92

You can use gradient descent by calling `train_with_optimization`: https://github.com/AtheMathmo/rusty-machine/blob/d049f60a3b55184e4d15098c7aa8db04afa76c06/src/learning/lin_reg.rs#L151-L160

**Comment by nikhilmitrax** [comment]
Thank you very much for pointing that out! I missed it the first time I read the code.
