### ISSUE TITLE
Flatten directory structure.

### ISSUE THREAD

**Issue by danlrobertson** [AtheMathmo/rusty-machine#34]
Is there any reason for the current structure? We could "flatten" the structure. For example.

```
$ tree -d -L 2
.
└── rusty-machine
    ├── benches
    ├── src
    ├── target
    └── tests
```

Becomes

```
$ tree -d -L 1
.
├── benches
├── src
├── target
└── tests
```

For larger projects I prefer the current structure, but at its current size, it might be easier to flatten a bit. Just a thought/nit.

**Comment by AtheMathmo** [comment]
Thanks for opening this issue. The reasoning for the current structure was as I had planned to pull out the linear algebra as a separate crate (but keep it in the same repository). Like so:

```
$ tree -d -L 2
.
└── rusty-machine
    ├── benches
    ├── src
    ├── target
    └── tests
└── rusty-linalg
    ├── benches
    ├── src
    ├── target
    └── tests
```

Right now I am still trying to figure out how best to do this and I see two options.

1. Keep the current structure and simply _move_ the linalg module into a new crate (keeping the code largely the same).
2. Make linalg data-structure agnostic (use pointers everywhere etc.) and place into it's own repository. Keep the `Matrix` struct a part of rusty-machine.

There are other options too. I think it is likely I will adopt option 1 for now and then have option 2 as a long term goal.

I'm not sure what the timing will be and so it may be worth flattening the structure now and reevaluating later. I'd like to keep this issue open to discuss this - it's the kind of decision I'm terrible at making!

**Comment by danlrobertson** [comment]
Ah! I see... 

> Keep the current structure and simply move the linalg module into a new crate (keeping the code largely the same).

I think this is a good idea too. There could be developers that could use the linear algebra module that may not want the machine learning component. This isn't a big deal now, since the repo is small, but in the future this could be an issue. Also, if the `linalg` module is maintained in a separate repo and crate, breaking changes in the `linalg` crate wouldn't have to immediately affect the `learning` crate. If you still want to keep them somewhat grouped you could create a GitHub organization... Again, just a thought... And probably something that should be a future goal vs one that should be addressed immediately.

**Comment by AtheMathmo** [comment]
I am planning on readdressing this soon. I'll keep this issue open and we can reassess in a couple weeks.

If any other readers have some input on this please chime in!
