### ISSUE TITLE
Singular value decomposition

### ISSUE THREAD

**Issue by zackmdavis** [AtheMathmo/rusty-machine#40]
There exist more efficient algorithms, but just using an eigenbasis of AᵀA is probably okay to start with? I understand this should also get us principal components analysis pretty easily.

**Comment by AtheMathmo** [comment]
I want to see SVD added for sure! Please feel free to work on it.

There currently exists some eigendecomposition. The eigenvalue decomposition works too but only for normal matrices with real eigenvalues. That in itself can probably be improved a lot.

See [here](https://github.com/AtheMathmo/rusty-machine/blob/master/rusty-machine/src/linalg/matrix/decomposition.rs#L347-L610) for the current code. If you want to make any changes, or have suggestions, let me know!

_Note: The current implementations are also just inefficient and should make use of the new `MatrixSlice` structs._

**Comment by AtheMathmo** [comment]
https://gist.github.com/zackmdavis/e65e295205aba03b548011c7401bf9ec

Posting this here for reference.

**Comment by AtheMathmo** [comment]
I've just merged the PR that resolves #64, sorry it took so long!. @zackmdavis - are you happy to pick up this issue again?

**Comment by AtheMathmo** [comment]
I found a [UofTexas paper](http://www.cs.utexas.edu/users/inderjit/public_papers/HLA_SVD.pdf) which provides pseudo code implementations of _lots_ of SVD algorithms. These may be a little out of scope to begin with - but some of the simpler ones may still be worth a look.

**Comment by AtheMathmo** [comment]
This issue was moved to AtheMathmo/rulinalg#4
