### ISSUE TITLE
eigenvalue computation is wrong sometimes

### ISSUE THREAD

**Issue by zackmdavis** [AtheMathmo/rusty-machine#46]
```rust
#[cfg(test)]
mod tests {
    use linalg::matrix::Matrix;

    #[test]
    fn eigentest() {
        // Let's consider the real, symmetric matrix
        // ⎡ 85 -30⎤
        // ⎣-30  40⎦.
        //
        // Example 2 in §8.3 of Otto Bretscher's _Linar Algebra with
        // Applications_, 3rd ed'n. mentions that the eigenvalues are 100 and
        // 25.
        //
        // NumPy agrees:
        //
        // ```
        // in [11]: a
        // Out[11]:
        // array([[ 85, -30],
        //        [-30,  40]])
        //
        // in [12]: linalg.eig(a)
        // Out[12]:
        // (array([ 100.,   25.]), array([[ 0.89442719,  0.4472136 ],
        //         [-0.4472136 ,  0.89442719]]))
        // ```
        //
        // Unfortunately, rusty-machine does not agree (as of 13 April's
        // 296d04dc7).

        let a = Matrix::<f64>::new(2,2,vec![85., -30., -30., 40.]);

        let eigenvals = a.eigenvalues();
        let (eigenvals_redux, eigenvecs) = a.eigendecomp();

        // The `eigenvalues` and `eigendecomp` methods agree with _each other_
        for i in 0..2 {
            assert_eq!(eigenvals[i], eigenvals_redux[i])
        }

        // But ...
        println!("λ₁, λ₂ = {:?}", eigenvals);

        assert!((eigenvals[0] == 100.) || (eigenvals[1] == 100.));
        assert!((eigenvals[0] == 25.) || (eigenvals[1] == 25.));

        //---- linalg::matrix::decomposition::tests::test_eigendecomp stdout ----
	// λ₁, λ₂ = [85, 40]
        // thread 'linalg::matrix::decomposition::tests::test_eigendecomp'
        // panicked at 'assertion failed: (eigenvals[0] == 100.) ||
        // (eigenvals[1] == 100.)', src/linalg/matrix/decomposition.rs:736
    }

}
```

**Comment by AtheMathmo** [comment]
Thanks for spotting this! I don't find it that surprising...

I made a bit of a mess as I wrote this up. It should be a lot easier now that we have MatrixSliceMut (though some other helper methods may be needed).

I'll take another look at this when I have time but it would definitely help to have you explore it. I can't find the exact source I used to get the algorithm (still looking, sorry!). But I believe it's a double-shifted implicit QR algorithm. Feel free to completely rewrite it if you want - I think the performance of the current implementation is pretty subpar too...

**Comment by AtheMathmo** [comment]
The bug occurs because the matrix is 2x2 and the current implementation doesn't handle this case. To fix this we could check if the matrix is 2x2 and if so explicitly compute the eigenvalues.

I welcome other solutions though!

**Comment by zackmdavis** [comment]
Oh, thanks, I can probably pull-request that tomorrow morning.

**Comment by AtheMathmo** [comment]
That would be awesome! [Probably redundant source.](http://www.math.harvard.edu/archive/21b_fall_04/exhibits/2dmatrices/index.html).

The code doesn't need to be tidy - the whole thing should undergo a cleanup soon anyway. (If you want to be the guy to make that happen I wont object!).

Are you still planning on giving SVD a go afterwards?

**Comment by AtheMathmo** [comment]
PR #47 closes this issue.
