### ISSUE TITLE
Implement `Into<Vec>` for `Matrix` and slices

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#59]
This would let us construct new matrices from old thanks to #53 . We can also use this to `reshape` a Matrix. e.g. `let new_mat = Matrix::new(x, y, old_mat)`.

@zackmdavis this seems like it might be one for you : )

**Comment by zackmdavis** [comment]
I'm not convinced we actually want this. Getting the data vector from a matrix loses the information about shape and therefore seems like a fundamentally different kind of "conversion" than that between, say, `&str` and `String` (which both represent the same Platonic string but with different implementation details). But see #72 for another idea on how to use `From`/`Into` to commission new matrices from existing slices.

**Comment by AtheMathmo** [comment]
Yes I think you're right - for now at least it seems like an abuse of the conversion tools. Maybe we'l reassess at a later date :)
