### ISSUE TITLE
Build failed:  use of unstable library feature "drain"  on matrix.rs  

### ISSUE THREAD

**Issue by raulsi** [AtheMathmo/rusty-machine#6]
build failed in rust v1.4. use of unstable library feature "drain"  
in :: src\linalg\matrix.rs:1059

`h_full_data.extend(holder_data.drain(..m-i)); `

**Comment by AtheMathmo** [comment]
This is because you need to update to the latest stable rust build: 1.6.0. It came out yesterday :)

**Comment by raulsi** [comment]
ok :)
