### ISSUE TITLE
Adding some examples

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#74]
It would be helpful to provide some example usage for our new users. This should hopefully provide implementations of some classic examples: Iris flower data set, MNIST handwritten digits, etc.

**Comment by ic** [comment]
I'll be working on MNIST with this week spare time, actually, and the current API (i.e. no convolution layer).

Just seeing this issue now. In the mean time, we should soon have something usable out of https://github.com/AtheMathmo/rusty-machine/pull/80.

**Comment by AtheMathmo** [comment]
MNIST would be awesome! The neural net stuff in rusty-machine is very primitive at the moment - it could definitely do with some work.

If you are familiar with nnets and want to try implementing some of that stuff yourself I would be more than happy to provide some guidance. I plan to tackle them myself at some point but have other things I'd rather tend to first.

As for this issue - I think your work in #80 justifies closing this ticket. Of course we shall continue working on the examples and maybe add some tutorials etc. soon. Thanks for all your help!

**Comment by ic** [comment]
I do have suggestions/ideas on the NNET side of the crate. Examples first as a "test harness".

**Comment by AtheMathmo** [comment]
@ic - Once you've had some time to play with some examples feel free to add to #91 .
