### ISSUE TITLE
Implement OpAssign traits for Vector

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#86]
Should be able to follow the same procedure as used in the [`matrix/impl_ops module`](https://github.com/AtheMathmo/rusty-machine/blob/v0.3.1/rusty-machine/src/linalg/matrix/impl_ops.rs#L528-L616). The relevant macros are `impl_op_assign_mat_scalar` and `impl_op_assign_mat`.

Implement the following:

- {`Add`, `Sub`, `Mul`, `Div`}`Assign` for `Vector` op SCALAR
- {`Add`, `Sub`}`Assign` for `Vector` op `Vector`

Labelled easy as the existing code can be very easily adapted for this purpose.

**Comment by DarkDrek** [comment]
I want to do this. Where should the new macros and tests be placed? Is vector.rs ok?

**Comment by AtheMathmo** [comment]
Awesome!

Yes I think sticking them in `vector.rs` is fine for now. I separated out the `matrix.rs` module as it was getting pretty huge. The vector one is close but I think is fine in one module for now :).

If you need any other guidance implementing these then let me know.
