### ISSUE TITLE
Linear and Logistic Regression clone parameters

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#92]
Currently the methods to return the parameters look like this:

```rust
pub fn parameters(&self) -> Option<Vector<f64>> {
    match *self.base.parameters() {
        Some(ref p) => Some(p.clone()),
        None => None,
    }
}
```

It would be more appropriate to return an `&Option<Vector<f64>>`. This would allow the user to control when to clone the data. The new methods will look like this:

```rust
pub fn parameters(&self) -> &Option<Vector<f64>> {
    &self.parameters
}
```

**Comment by DarkDrek** [comment]
Wouldn't it be better to return a `Option<&Vector<f64>>` since we don't actually want to share the option but rather data if available? This has also the charm of allowing the user to clone with `.cloned()` instead of `.unwrap()`.

```rust
pub fn parameters(&self) -> Option<&Vector<f64>> {
    self.parameters.as_ref()
}
```

**Comment by AtheMathmo** [comment]
I think you're right! This does indeed seem like a cleaner solution to me.

We should probably adopt this same pattern in a few other places where I am currently returning `&Option<T>`. I believe this is only in the `learning` module (within model code).

**Comment by DarkDrek** [comment]
I would try to find these places and make a single PR to change all of them including the ones mentioned in this issue. Ok?

**Comment by AtheMathmo** [comment]
Awesome! Thanks.
