### ISSUE TITLE
Implement `IntoIterator` for `MatrixSlice` and `MatrixSliceMut`

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#94]
We currently implement an `iter()` method for each of the above. However it would be nice to be able to consume the slice into an iterator so that we release ownership of the underlying data.

This issue should use the [`IntoIterator`](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html) trait. The existing slice `iter()` methods should suffice within these implementations.

**Comment by DarkDrek** [comment]
I'm a bit confused `MatrixSlice` doesn't seem to have ownership of data it just borrows data from a `Matrix`?

**Comment by AtheMathmo** [comment]
Yes, that's correct.

I'm actually a little unsure about this issue - shortly after writing it I had doubts. My initial thoughts were:

- Consuming the slice into an iterator may be useful.
- Being able to use the `for _ in slice` syntax would be nice.
- In general `IntoIterator` is a commonly used and valuable trait to implement.

But in hindsight I'm not sure that the first is particularly useful. And additionally the second is a little confusing - would every user expect the iteration over a matrix to be over elements in row-major order?

I'd like to hear your thoughts on it too.

**Comment by DarkDrek** [comment]
- Consuming the slice doesn't work since it implements `Copy`
- Since it is a view for collection I would expect to be able to iterate over it naturally. The (default) iteration order has to be documented somewhere. The simple syntax wouldn't be good when we want to equally support different ways of iterating (row or column based).

Overall I'm still in favor of supporting it since row-major order will be the default because it's faster. So if we have column-major iteration the user will have to explicitly request it.

**Comment by AtheMathmo** [comment]
Yeah you are right with the first point - though `MatrixSliceMut` does not implement copy. Perhaps it should...

My point about iteration was more about whether users would expect to iterate over rows, or single elements? For example - iterating over a numpy array (`for x in arr:`) will iterate over rows. Of course we don't need to follow this convention - but I wanted to raise the question anyway.

**Comment by DarkDrek** [comment]
Since we have other methods to iterate over rows (iter_rows) I find i more intuitive that `for x in arr` gives me single elements and the other ways of iterating are explicit. I would expect that `arr.into_iter()` uses roughly the same logic as `arr.iter()`

**Comment by AtheMathmo** [comment]
Yes I think I agree. In which case - I think it should be enough to simple call `arr.iter()` inside the `IntoIterator` implementation.
